export let clustersNum = 3;
export let PARAM = 0.00001;
export let data = [];
export let AfterNormalizeData = [];
export let cluster = [];
export let City = ['Тольятти', 'Самара', 'Чапаевск'];
export let operationDistant =[]
export let FilterOperationDistant=[];
export let Color = ['green', 'purple', 'black'];
export let quantity = 100;